version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: maauu
    ports:
      - "3306:3306"  # Map host machine's port 3306 to container's port 3306
    volumes:
      - ./mysql_data:/var/lib/mysql  # Mount a volume for persistent data